// Custom Worker entry point wrapping OpenNext's generated Next.js handler.
//
// Why this file exists: Next.js App Router Route Handlers do not support
// WebSocket upgrades (https://github.com/vercel/next.js/discussions/95514),
// and the proposed fix explicitly excludes Edge/Workers runtimes -- so the
// portal's live document collaboration (Durable Object + WebSocket) can
// never be reached through a Next.js route, on any Next.js version, on this
// platform. This wrapper intercepts the WebSocket upgrade for a document
// room's path before the request reaches Next.js at all, verifies the
// session cookie against PORTAL_DB itself (no next/headers available here),
// and forwards every other request to the OpenNext-generated handler
// unchanged. Pattern per https://opennext.js.org/cloudflare/howtos/custom-worker.
//
// wrangler.jsonc's `main` points here instead of directly at
// `.open-next/worker.js`. See RHPS Portal plan, section B, for the full
// rationale (plan file: ~/.claude/plans/it-s-working-well-let-s-wobbly-russell.md).

export { DocumentRoom } from "./documentRoom";
// `.open-next/worker.js` is generated by `npm run pages:build`; it doesn't
// exist in a fresh checkout until then.
import { default as nextHandler } from "./.open-next/worker.js";

const ROOM_PATH_PATTERN = /^\/portal\/api\/documents\/([^/]+)\/room$/;

function parseCookie(cookieHeader: string | null, name: string): string | null {
  if (!cookieHeader) return null;
  for (const part of cookieHeader.split(";")) {
    const [key, ...rest] = part.trim().split("=");
    if (key === name) return decodeURIComponent(rest.join("="));
  }
  return null;
}

// Deterministic per-user cursor color so the same person gets the same
// color across sessions, without storing a color choice anywhere.
const CURSOR_COLORS = ["#0F4D3A", "#234A6F", "#C47A52", "#7A3B69", "#2B7A78", "#8A5A2B"];
function colorForUserId(userId: string): string {
  let hash = 0;
  for (let i = 0; i < userId.length; i++) hash = (hash * 31 + userId.charCodeAt(i)) >>> 0;
  return CURSOR_COLORS[hash % CURSOR_COLORS.length];
}

async function verifySessionForRoom(
  request: Request,
  env: Env,
): Promise<{ userId: string; userName: string; isPlatformAdmin: boolean } | null> {
  const token = parseCookie(request.headers.get("Cookie"), "portal_session");
  if (!token) return null;

  const row = await env.PORTAL_DB.prepare(
    `SELECT portal_users.id AS id, portal_users.name AS name, portal_users.status AS status,
            portal_users.is_platform_admin AS is_platform_admin,
            portal_sessions.expires_at AS expires_at
     FROM portal_sessions
     JOIN portal_users ON portal_users.id = portal_sessions.user_id
     WHERE portal_sessions.id = ?`,
  )
    .bind(token)
    .first<{ id: string; name: string; status: string; is_platform_admin: number; expires_at: string }>();

  if (!row) return null;
  if (row.status !== "Active") return null;
  if (new Date(row.expires_at).getTime() <= Date.now()) return null;

  return { userId: row.id, userName: row.name, isPlatformAdmin: Boolean(row.is_platform_admin) };
}

// Mirrors lib/portalPermissions.ts's getDocumentAccessLevel -- duplicated
// rather than imported because this file runs outside the Next.js request
// context (no next/headers), and the shared function's signature is small
// enough that keeping two copies in sync is simpler than restructuring the
// permissions module to be import-safe from both places.
function documentAccessLevel(
  identity: { userId: string; isPlatformAdmin: boolean },
  document: { uploader_user_id: string; visibility: string },
  shares: { user_id: string; permission: string }[],
): "none" | "view" | "edit" {
  if (document.uploader_user_id === identity.userId) return "edit";
  if (identity.isPlatformAdmin) return "edit";
  if (document.visibility === "Shared") return "edit";
  const share = shares.find((s) => s.user_id === identity.userId);
  if (!share) return "none";
  return share.permission === "Edit" ? "edit" : "view";
}

export default {
  // No explicit parameter types here: inferred from `satisfies
  // ExportedHandler<Env>` so `request` is exactly the "incoming request"
  // flavor the generated Workers types expect, matching
  // open-next-worker.d.ts's declaration for `nextHandler.fetch` below.
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const roomMatch = url.pathname.match(ROOM_PATH_PATTERN);

    if (roomMatch && request.headers.get("Upgrade") === "websocket") {
      const documentId = roomMatch[1];
      const identity = await verifySessionForRoom(request, env);
      if (!identity) return new Response("Not signed in.", { status: 401 });

      const document = await env.PORTAL_DB.prepare(
        "SELECT doc_type, uploader_user_id, visibility FROM documents WHERE id = ?",
      )
        .bind(documentId)
        .first<{ doc_type: string; uploader_user_id: string; visibility: string }>();
      if (!document || document.doc_type !== "richtext") {
        return new Response("Not found.", { status: 404 });
      }

      // Private-document gate: a "none" access level never reaches the
      // Durable Object at all, and "view" reaches it but is passed through
      // as read-only (see documentRoom.ts's per-connection canEdit check) --
      // this is the hard boundary; CollaborativeEditor's client-side
      // readOnly toggle is only a UX nicety layered on top of it.
      const { results: shareRows } = await env.PORTAL_DB.prepare(
        "SELECT user_id, permission FROM document_shares WHERE document_id = ?",
      )
        .bind(documentId)
        .all<{ user_id: string; permission: string }>();
      const access = documentAccessLevel(identity, document, shareRows);
      if (access === "none") return new Response("Not found.", { status: 404 });

      const forwardedRequest = new Request(request, {
        headers: new Headers(request.headers),
      });
      forwardedRequest.headers.set("X-Portal-User-Id", identity.userId);
      forwardedRequest.headers.set("X-Portal-User-Name", identity.userName);
      forwardedRequest.headers.set("X-Portal-User-Color", colorForUserId(identity.userId));
      forwardedRequest.headers.set("X-Portal-Can-Edit", access === "edit" ? "1" : "0");

      const stub = env.DOCUMENT_ROOM.getByName(documentId);
      return stub.fetch(forwardedRequest);
    }

    return nextHandler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;
